### ISSUE TITLE
push error when sending to iPhone 4S/Sprint

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#145]
]: at=info method=POST path="/api/v1/messages/" host=push.zom.im request_id=b077d96d-dafd-4a12-ae6a-0bd01e2f4e6c fwd="209.6.147.165,162.158.60.95" dyno=web.1 connect=0ms service=339ms status=202 bytes=285
2016-05-26T17:57:11.275329+00:00 app[worker.1]: Exception sending APNS message. TypeError : Odd-length string
2016-05-26T17:57:11.275341+00:00 app[worker.1]: Traceback (most recent call last):
2016-05-26T17:57:11.275342+00:00 app[worker.1]:   File "/app/push/messages/messenger.py", line 52, in _send_apns
2016-05-26T17:57:11.275343+00:00 app[worker.1]:     apns_send_bulk_message(registration_ids, message, **kwargs)
2016-05-26T17:57:11.275344+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 223, in apns_send_bulk_message
2016-05-26T17:57:11.275345+00:00 app[worker.1]:     _apns_send(registration_id, alert, identifier=identifier, socket=socket, **kwargs)
2016-05-26T17:57:11.275346+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 148, in _apns_send
2016-05-26T17:57:11.275346+00:00 app[worker.1]:     frame = _apns_pack_frame(token, json_data, identifier, expiration_time, priority)
2016-05-26T17:57:11.275347+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 66, in _apns_pack_frame
2016-05-26T17:57:11.275347+00:00 app[worker.1]:     token = unhexlify(token_hex)
2016-05-26T17:57:11.275348+00:00 app[worker.1]: TypeError: Odd-length string
2016-05-26T17:57:11.275480+00:00 app[worker.1]: [2016-05-26 12:57:11,274: ERROR/Worker-8] Exception sending APNS message. TypeError : Odd-length string
2016-05-26T17:57:11.275481+00:00 app[worker.1]: Traceback (most recent call last):
2016-05-26T17:57:11.275481+00:00 app[worker.1]:   File "/app/push/messages/messenger.py", line 52, in _send_apns
2016-05-26T17:57:11.275482+00:00 app[worker.1]:     apns_send_bulk_message(registration_ids, message, **kwargs)
2016-05-26T17:57:11.275482+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 223, in apns_send_bulk_message
2016-05-26T17:57:11.275483+00:00 app[worker.1]:     _apns_send(registration_id, alert, identifier=identifier, socket=socket, **kwargs)
2016-05-26T17:57:11.275483+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 148, in _apns_send
2016-05-26T17:57:11.275484+00:00 app[worker.1]:     frame = _apns_pack_frame(token, json_data, identifier, expiration_time, priority)
2016-05-26T17:57:11.275484+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 66, in _apns_pack_frame
2016-05-26T17:57:11.275485+00:00 app[worker.1]:     token = unhexlify(token_hex)
2016-05-26T17:57:11.275485+00:00 app[worker.1]: TypeError: Odd-length string
2016-05-26T17:57:11.297078+00:00 app[worker.1]: [2016-05-26 12:57:11,296: INFO/Worker-8] Starting new HTTPS connection (1): api.keen.io
2016-05-26T17:57:11.514824+00:00 app[worker.1]: [2016-05-26 12:57:11,514: WARNING/Worker-8] pyrollbar: No access_token provided. Please configure by calling rollbar.init() with your access token.
2016-05-26T17:57:11.515557+00:00 app[worker.1]: [2016-05-26 12:57:11,515: INFO/MainProcess] Task messages.messenger._task_send_apns[efeab5f4-b437-44ad-b939-b98f0546af80] succeeded in 0.51198031567s: None

**Comment by n8fr8** [comment]
Here is the client request from Zom Android 

D/PushSecureClient(21293): Request -> POST https://push.zom.im/api/v1/messages/
D/PushSecureClient(21293): token=62480647c007b398ac09daa22c6b8266e8500a3f&data=
D/PushSecureClient(21293): Response <- 202 https://push.zom.im/api/v1/messages/
D/PushSecureClient(21293): OkHttp-Selected-Protocol: h2
D/PushSecureClient(21293): date: Thu, 26 May 2016 19:01:06 GMT
D/PushSecureClient(21293): content-type: application/json
D/PushSecureClient(21293): set-cookie: __cfduid=dfa93096eac57e0bf11b429b2ce484f901464289266; expires=Fri, 26-May-17 19:01:06 GMT; path=/; domain=.zom.im; HttpOnly
D/PushSecureClient(21293): vary: Accept, Cookie
D/PushSecureClient(21293): allow: POST, OPTIONS
D/PushSecureClient(21293): via: 1.1 vegur
D/PushSecureClient(21293): server: cloudflare-nginx
D/PushSecureClient(21293): cf-ray: 2a93794b00e82210-EWR
D/PushSecureClient(21293): OkHttp-Sent-Millis: 1464289266030
D/PushSecureClient(21293): OkHttp-Received-Millis: 1464289266138
D/PushSecureClient(21293): 
D/PushSecureClient(21293): {"token":"62480647c007b398ac09daa22c6b8266e8500a3f","data":null}

**Comment by n8fr8** [comment]
After editing the APNS to remove spaces, the push worked once, but now subsequent pushes are still getting the same error:

2016-05-28T01:52:29.561744+00:00 heroku[router]: at=info method=PUT path="/api/v1/device/apns/3e446a28-711c-4836-b3d0-adbf4d7b20af/" host=push.zom.im request_id=64e41890-c7ef-433d-acf4-9d221b547dd7 fwd="74.73.227.37,173.245.52.121" dyno=web.1 connect=0ms service=49ms status=200 bytes=490
2016-05-28T02:22:00.195378+00:00 heroku[router]: at=info method=POST path="/api/v1/messages/" host=push.zom.im request_id=c22805cb-8337-4dba-97d1-2788eadf59b7 fwd="172.56.22.28,108.162.219.188" dyno=web.1 connect=1ms service=60ms status=202 bytes=285
2016-05-28T02:22:00.208808+00:00 app[worker.1]: [2016-05-27 21:22:00,208: INFO/MainProcess] Received task: messages.messenger._task_send_apns[7e4369e0-611a-4e6d-8d6a-437dae1901cd]
2016-05-28T02:22:00.288839+00:00 app[worker.1]: Exception sending APNS message. TypeError : Odd-length string
2016-05-28T02:22:00.288849+00:00 app[worker.1]: Traceback (most recent call last):
2016-05-28T02:22:00.288851+00:00 app[worker.1]:   File "/app/push/messages/messenger.py", line 52, in _send_apns
2016-05-28T02:22:00.288852+00:00 app[worker.1]:     apns_send_bulk_message(registration_ids, message, **kwargs)
2016-05-28T02:22:00.288854+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 223, in apns_send_bulk_message
2016-05-28T02:22:00.288855+00:00 app[worker.1]:     _apns_send(registration_id, alert, identifier=identifier, socket=socket, **kwargs)
2016-05-28T02:22:00.288856+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 148, in _apns_send
2016-05-28T02:22:00.288864+00:00 app[worker.1]:     frame = _apns_pack_frame(token, json_data, identifier, expiration_time, priority)
2016-05-28T02:22:00.288864+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 66, in _apns_pack_frame
2016-05-28T02:22:00.288865+00:00 app[worker.1]:     token = unhexlify(token_hex)
2016-05-28T02:22:00.288866+00:00 app[worker.1]: TypeError: Odd-length string
2016-05-28T02:22:00.289368+00:00 app[worker.1]: [2016-05-27 21:22:00,285: ERROR/Worker-3] Exception sending APNS message. TypeError : Odd-length string
2016-05-28T02:22:00.289374+00:00 app[worker.1]: Traceback (most recent call last):
2016-05-28T02:22:00.289376+00:00 app[worker.1]:   File "/app/push/messages/messenger.py", line 52, in _send_apns
2016-05-28T02:22:00.289377+00:00 app[worker.1]:     apns_send_bulk_message(registration_ids, message, **kwargs)
2016-05-28T02:22:00.289378+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 223, in apns_send_bulk_message
2016-05-28T02:22:00.289379+00:00 app[worker.1]:     _apns_send(registration_id, alert, identifier=identifier, socket=socket, **kwargs)
2016-05-28T02:22:00.289380+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 148, in _apns_send
2016-05-28T02:22:00.289380+00:00 app[worker.1]:     frame = _apns_pack_frame(token, json_data, identifier, expiration_time, priority)
2016-05-28T02:22:00.289381+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 66, in _apns_pack_frame
2016-05-28T02:22:00.289382+00:00 app[worker.1]:     token = unhexlify(token_hex)
2016-05-28T02:22:00.289383+00:00 app[worker.1]: TypeError: Odd-length string
2016-05-28T02:22:00.320254+00:00 app[worker.1]: [2016-05-27 21:22:00,320: INFO/Worker-3] Starting new HTTPS connection (1): api.keen.io
2016-05-28T02:22:02.249963+00:00 app[worker.1]: [2016-05-27 21:22:02,249: WARNING/Worker-3] pyrollbar: No access_token provided. Please configure by calling rollbar.init() with your access token.
2016-05-28T02:22:02.263407+00:00 app[worker.1]: [2016-05-27 21:22:02,263: INFO/MainProcess] Task messages.messenger._task_send_apns[7e4369e0-611a-4e6d-8d6a-437dae1901cd] succeeded in 2.05156920606s: None

**Comment by chrisballinger** [comment]
Her device must be updating the APNS token again to the incorrect hex
string. I still don't see how it is possible to make this happen with the
latest code in develop, but we could just add some code on the server to
sanitize it anyway.

**Comment by n8fr8** [comment]
It is happening and I can guarantee she has the latest version. There is
some difference you arent considering. 

Sanitization is a good stop gap.

is there a way to log the raw bytes that Apple is giving?

**Comment by n8fr8** [comment]
2016-05-28T02:22:00.288865+00:00 app[worker.1]: token = unhexlify(token_hex)
2016-05-28T02:22:00.288866+00:00 app[worker.1]: TypeError: Odd-length string

**Comment by n8fr8** [comment]
Registration ID: a7aa6f08 fcb8c376 0d9836fb 357c52c0 56370986 ff36f114 8f62026e 006eeb86

**Comment by gekhung** [comment]
iTouch 5/iOS 9.3.2: I am not sure if this is similar error, but mine had the push screen and the Congratulations page appear twice once I clicked on the Push button.
