### ISSUE TITLE
zom push is failing

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#335]
Thiis from the Heroku logs

Exception sending APNS message. ConnectionFailed : 
2017-05-17T16:17:58.462856+00:00 app[web.1]: Traceback (most recent call last):
2017-05-17T16:17:58.462862+00:00 app[web.1]:     client = _apns_create_socket(certfile=certfile, application_id=application_id)
2017-05-17T16:17:58.462865+00:00 app[web.1]: ConnectionFailed
2017-05-17T16:17:58.462863+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 40, in _apns_create_socket
2017-05-17T16:17:58.608386+00:00 app[web.1]: push-sent: {'exception': 'ConnectionFailed : ', 'using_sandbox': False}
2017-05-17T16:17:58.462863+00:00 app[web.1]:     client.connect()
2017-05-17T16:17:58.462864+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/apns2/client.py", line 163, in connect
2017-05-17T16:17:58.462864+00:00 app[web.1]:     raise ConnectionFailed()
2017-05-17T16:17:58.619080+00:00 heroku[router]: at=info method=POST path="/api/v1/messages/" host=push.zom.im request_id=ef8cc16a-02dc-4787-8d8a-1a2aee60c732 fwd="45.55.5.246,172.68.141.233" dyno=web.1 connect=0ms service=474ms status=202 bytes=254 protocol=http
2017-05-17T16:17:58.675826+00:00 app[web.1]: push-sent: {'exception': 'ConnectionFailed : ', 'using_sandbox': False}
2017-05-17T16:17:58.912727+00:00 app[web.1]: Exception sending APNS message. ConnectionFailed : 
2017-05-17T16:17:58.912731+00:00 app[web.1]: Traceback (most recent call last):
2017-05-17T16:17:58.912732+00:00 app[web.1]:   File "/app/push/messages/messenger.py", line 56, in _send_apns
2017-05-17T16:17:58.912733+00:00 app[web.1]:     apns_send_bulk_message(registration_ids, message, **kwargs)
2017-05-17T16:17:58.912735+00:00 app[web.1]:     certfile=certfile, **kwargs
2017-05-17T16:17:58.912736+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 66, in _apns_send
2017-05-17T16:17:58.912734+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 137, in apns_send_bulk_message
2017-05-17T16:17:58.912737+00:00 app[web.1]:     client = _apns_create_socket(certfile=certfile, application_id=application_id)
2017-05-17T16:17:58.912738+00:00 app[web.1]:     client.connect()
2017-05-17T16:17:58.689545+00:00 heroku[router]: at=info method=POST path="/api/v1/messages/" host=push.zom.im request_id=73ca7e52-e359-4146-8480-ffc225daccb1 fwd="45.55.5.246,172.68.141.235" dyno=web.1 connect=0ms service=521ms status=202 bytes=254 protocol=http
2017-05-17T16:17:58.912739+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/apns2/client.py", line 163, in connect
2017-05-17T16:17:58.912737+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/push_notifications/apns.py", line 40, in _apns_create_socket
2017-05-17T16:17:58.912739+00:00 app[web.1]:     raise ConnectionFailed()

**Comment by chrisballinger** [comment]
The APNS certificate most likely needs to be regenerated.

**Comment by n8fr8** [comment]
Is that something that needs to be done on a regular basis? Where do I begin?

**Comment by n8fr8** [comment]
I don't even see a Push certificate in our acccount (https://developer.apple.com/account/ios/certificate/). 

Was this perhaps registered under your or David's accounts?

**Comment by chrisballinger** [comment]
Wow looks like there's no longer a cert at all, which means it probably expired. Looks like I have access to generate one, so I'll sort it out.

**Comment by chrisballinger** [comment]
Actually I don't have the access I need. It won't let me generate certs or edit the app Id info.

**Comment by n8fr8** [comment]
Are you sure it was in our account? I guess it would have to be. I will check your account access.

**Comment by n8fr8** [comment]
(I can't believe we didn't get an email or warning from Apple... sheesh!)

**Comment by n8fr8** [comment]
You are now an admin.
